apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lamp-service
  name: lamp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-service
  strategy: {}
  template:
    metadata:
      labels:
        app: lamp-service
    spec:
      containers:
      - image: shadadelic/lamp-service:1
        name: lamp-service
        resources: {}
        volumeMounts:
        - name: config-volume
          mountPath: /application/config.yml
          subPath: config.yml
        env:
          - name: DATABASE_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: lamp-service-secret
                key: database-connection-string
                optional: false 
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: lamp-service-secret
                key: database-password
                optional: false 
      volumes:
        - name: config-volume
          configMap:
            name: lamp-service-configmap