apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp-configmap
  namespace: lamp
data:
  config.yml: |
    server:
      # Change admin context path as both http and admin endpoint are available 
      # under the same context through the ingress controller.
      adminContextPath: /admin
      applicationConnectors:
        - type: http
          port: ${APP_PORT:-8080}
    logging:
      level: INFO
      loggers:
        leanix.net: DEBUG
    database:
      driverClass: org.postgresql.Driver
      user: lamp_user@psql-lamp-local
      password: ${DATABASE_PASSWORD}
      # e.g. jdbc:postgresql://psql-lamp-local.postgres.database.azure.com/psqldb-lamp
      url: ${DATABASE_CONNECTION_STRING}
      properties:
        charSet: UTF-8
      maxWaitForConnection: 1s
      validationQuery: "SELECT 1"
      validationQueryTimeout: 3s
