on:
  push:
    branches:
      - 'main'
env:
  APP_NAME: lamp
jobs:
  build-artifact:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build project with Maven
      run: mvn -B clean package 
    - run: ls -la && ls -la target/
    - uses: actions/upload-artifact@v1
      with:
        name: app-artifact
        path: target/lamp-service.jar
  build-image:
    runs-on: ubuntu-latest
    needs: build-artifact
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v1
      with:
          name: app-artifact
          path: target/
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - run: ls -la && ls -la target/
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: shadadelic/${{ env.APP_NAME }}-service:${{ github.run_attempt }}-${{ github.sha }}
  # Based on the following tutorial
  # Ref.: https://docs.microsoft.com/en-us/azure/aks/kubernetes-action
  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-image
    environment: dev
    steps:
    - uses: actions/checkout@v2
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks-lamp-development
        resource-group: lamp-service-development
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/src/main/manifests/aks/deployment.yaml
          ${{ github.workspace }}/src/main/manifests/aks/configmap.yaml
          ${{ github.workspace }}/src/main/manifests/aks/service.yaml
          ${{ github.workspace }}/src/main/manifests/aks/ingress-http.yaml
          ${{ github.workspace }}/src/main/manifests/aks/ingress-admin.yaml
        images: shadadelic/${{ env.APP_NAME }}-service:${{ github.run_attempt }}-${{ github.sha }}
        namespace: ${{ env.APP_NAME }}
  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: deploy-to-dev
    environment: prod
    steps:
    - uses: actions/checkout@v2
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: aks-lamp-production
        resource-group: lamp-service-production
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ${{ github.workspace }}/src/main/manifests/aks/deployment.yaml
          ${{ github.workspace }}/src/main/manifests/aks/configmap.yaml
          ${{ github.workspace }}/src/main/manifests/aks/service.yaml
          ${{ github.workspace }}/src/main/manifests/aks/ingress-http.yaml
          ${{ github.workspace }}/src/main/manifests/aks/ingress-admin.yaml
        images: shadadelic/${{ env.APP_NAME }}-service:${{ github.run_attempt }}-${{ github.sha }}
        namespace: ${{ env.APP_NAME }}